ID: str = 'id'
DATE: str = 'date'
PROGRAMMING_LANGUAGE: str = 'programming_language'
TIME_SPENT: str = 'time_spent'
RATING: str = 'rating'
PROGRAMMER_ID: str = 'programmer_id'
DESCRIPTION: str = 'description'
SELECT: str = 'SELECT'
INSERT: str = 'INSERT'
UPDATE: str = 'UPDATE'
DELETE: str = 'DELETE'
NAME: str = 'name'
SURNAME: str = 'surname'
PROGRAMMERS_DATABASE: str = 'programmers'
RECORDS_DATABASE: str = 'records'
TAGS_DATABASE: str = 'tags'
COLOR: str = 'color'
TAGGED_RECORDS_DATABASE: str = 'tagged_records'
RECORD_ID: str = 'record_id'
TAG_ID: str = 'tag_id'
TAG_IDS: str = 'tag_ids'
USERNAME: str = 'username'
EMAIL: str = 'email'
PASSWORD: str = 'password'
ISADMIN: str = 'admin'
LOGIN: str = 'login'
AUTHOR: str = 'author'
CONTENT: str = 'content'
NOTES_DATABASE: str = 'notes'
DATETIME_CREATED: str = 'datetime_created'
DATETIME_MODIFIED: str = 'datetime_modified'
URL: str = 'https://tda.knapa.cz/'
HEADERS = {
    "x-access-token": "9492a5fdccb71211fed377fcd8d47508"
}
CREATOR_ID: str = 'creator_id'
LINES_ADDED: str = 'lines_added'
LINES_REMOVED: str = 'lines_removed'
COMMIT_ID: str = 'commit_id'
COMMITS_DATABASE: str = 'commits'


